# Generated by Django 4.2.11 on 2024-04-15 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marketplace", models.CharField(max_length=100)),
                (
                    "marketplace_status",
                    models.CharField(max_length=100, null=True),
                ),
                ("lengow_status", models.CharField(max_length=100, null=True)),
                ("order_id", models.CharField(max_length=100)),
                ("order_amount", models.FloatField()),
                ("order_shipping", models.FloatField()),
                ("order_datetime", models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name="orders",
            constraint=models.UniqueConstraint(
                fields=("order_id", "marketplace"),
                name="unique_per_marketplace",
            ),
        ),
    ]
